### ISSUE TITLE
Deprecated warnings

### ISSUE THREAD

**Issue by saesrpg** [NodeBB/nodebb-plugin-gdpr#9]
Although these do not affect the plugin, I thought I would report it.

```
2019-02-06T14:12:57.376Z [4999/23748] - warn: [deprecated] requiring core modules with `module.parent.require('./database')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at Object.<anonymous> (/var/****/node_modules/nodebb-plugin-gdpr/library.js:5:24)
2019-02-06T14:12:57.377Z [4999/23748] - warn: [deprecated] requiring core modules with `module.parent.require('./meta')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at Object.<anonymous> (/var/****/node_modules/nodebb-plugin-gdpr/library.js:6:26)
2019-02-06T14:12:57.377Z [4999/23748] - warn: [deprecated] requiring core modules with `module.parent.require('./user')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at Object.<anonymous> (/var/****/node_modules/nodebb-plugin-gdpr/library.js:7:26)
2019-02-06T14:12:57.378Z [4999/23748] - warn: [deprecated] requiring core modules with `module.parent.require('./pagination')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at Object.<anonymous> (/var/****/node_modules/nodebb-plugin-gdpr/library.js:8:32)
```

**Comment by julianlam** [comment]
v1.0.6, sorry about that, forgot to publish the updated version.
